<?php

use Drupal\Core\DependencyInjection\ContainerBuilder;
use Drupal\Core\DependencyInjection\ServiceProviderInterface;
use Symfony\Component\DependencyInjection\Reference;

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function custom_slogan_preprocess_page(&$variables) {
  $new_slogan = 'Secxndary Slogan';
  \Drupal::configFactory()
    ->getEditable('system.site')
    ->set('slogan', $new_slogan)
    ->save();

  $variables['head_title']['slogan'] = $new_slogan;
}
